language: en
pipeline: supervised_embeddings

policies:
- batch_size: 50
  epochs: 200
  max_training_samples: 300
  name: KerasPolicy
- fallback_action_name: action_default_fallback
  name: FallbackPolicy
- max_history: 5
  name: MemoizationPolicy
- name: FormPolicy
- name: MappingPolicy
